In [11]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

%matplotlib inline

import requests
from bs4 import BeautifulSoup

In [12]:
gdp=pd.read_csv ('per capita gdp by state 050718(1).csv', header=4)
gdp

,Fips,Area,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,1-year (2016-2017),5-year (2013-2017),10-year (2008-2017),Unnamed: 15
0,1000,Alabama,36976,35376,35912,36210,36440,36674,36473,36818,37158,37508,0.9%,2.3%,1.4%,NaN
1,2000,Alaska,67527,72204,69565,70618,73505,69711,67179,65971,63304,63610,0.5%,-8.8%,-5.8%,NaN
2,4000,Arizona,41800,38232,37943,38267,38591,38352,38534,38787,38940,39583,1.7%,3.2%,-5.3%,NaN
3,5000,Arkansas,34957,33837,34674,35156,34982,35888,36265,36295,36502,36714,0.6%,2.3%,5.0%,NaN
4,6000,California,54454,51733,51878,52105,52963,53838,55571,57637,58974,60359,2.3%,12.1%,10.8%,NaN
5,8000,Colorado,51651,49731,49260,49303,49673,50523,52105,53007,52863,54026,2.2%,6.9%,4.6%,NaN
6,9000,Connecticut,68777,65574,64901,63602,63433,62438,62023,62796,62745,62633,-0.2%,0.3%,-8.9%,NaN
7,10000,Delaware,62535,64313,62844,63795,62182,60738,63555,64809,63578,63955,0.6%,5.3%,2.3%,NaN
8,11000,District of Columbia,170687,166178,168070,166908,163196,159264,159369,159530,159141,159607,0.3%,0.2%,-6.5%,NaN
9,12000,Florida,41241,38695,38610,37875,37711,38018,38466,39334,39608,39842,0.6%,4.8%,-3.4%,NaN
10,13000,Georgia,44239,42052,42032,42144,42206,42513,43467,44246,45238,45925,1.5%,8.0%,3.8%,NaN
11,15000,Hawaii,50833,48549,49422,49314,49479,49484,49591,51052,51964,52869,1.7%,6.8%,4.0%,NaN
12,16000,Idaho,36691,34664,34622,34291,34121,34787,35173,35679,36256,36441,0.5%,4.8%,-0.7%,NaN
13,17000,Illinois,51406,49859,50306,51189,52141,51919,52984,53709,54308,55102,1.5%,6.1%,7.2%,NaN
14,18000,Indiana,43515,40572,43000,43066,43077,43876,44818,44721,45717,46427,1.6%,5.8%,6.7%,NaN
15,19000,Iowa,46413,45195,45891,46546,48031,48034,49688,51379,52248,52284,0.1%,8.8%,12.6%,NaN
16,20000,Kansas,46050,43770,44250,45488,45513,45468,46235,46792,47548,47435,-0.2%,4.3%,3.0%,NaN
17,21000,Kentucky,37875,36209,37585,37933,38062,38259,38336,38419,38736,39277,1.4%,2.7%,3.7%,NaN
18,22000,Louisiana,46578,46949,48601,45722,45489,43721,44475,44751,44440,44372,-0.2%,1.5%,-4.7%,NaN
19,23000,Maine,38508,37910,38357,37787,37727,37508,38149,38415,39125,39521,1.0%,5.4%,2.6%,NaN
20,24000,Maryland,52877,52515,53679,54213,53999,53751,54108,54661,55786,56375,1.1%,4.9%,6.6%,NaN
21,25000,Massachusetts,60723,59178,60814,61766,62441,61842,62528,64660,65168,66500,2.0%,7.5%,9.5%,NaN
22,26000,Michigan,39863,36676,38766,39758,40465,40992,41544,42594,43330,44201,2.0%,7.8%,10.9%,NaN
23,27000,Minnesota,51234,48884,50153,50899,51297,52023,53109,53257,54295,54805,0.9%,5.3%,7.0%,NaN
24,28000,Mississippi,33128,31658,31687,31175,31807,31952,31635,31714,32334,32447,0.3%,1.5%,-2.1%,NaN
25,29000,Missouri,43118,42012,42207,41601,41941,42498,42527,42785,42736,43036,0.7%,1.3%,-0.2%,NaN
26,30000,Montana,37636,36667,37738,38578,38601,38567,39319,40148,40041,39833,-0.5%,3.3%,5.8%,NaN
27,31000,Nebraska,47770,47973,49571,51378,50655,51597,53109,54048,54660,54654,0.0%,5.9%,14.4%,NaN
28,32000,Nevada,49286,44774,44597,44559,43384,43074,43075,44057,44142,44812,1.5%,4.0%,-9.1%,NaN
29,33000,New Hampshire,47842,47265,48395,48509,48661,48873,49623,51020,51827,52509,1.3%,7.4%,9.8%,NaN
30,34000,New Jersey,57784,55067,55023,54281,55106,55659,55563,56196,56428,56776,0.6%,2.0%,-1.7%,NaN
31,35000,New Mexico,41207,40670,40300,40167,40098,39659,40769,41457,41334,41619,0.7%,4.9%,1.0%,NaN
32,36000,New York,58532,59481,61259,61163,62769,62320,63174,64286,64522,65220,1.1%,4.7%,11.4%,NaN
33,37000,North Carolina,45567,43160,43071,43169,42619,42909,43400,44180,44194,44706,1.2%,4.2%,-1.9%,NaN
34,38000,North Dakota,48379,48858,52186,57120,68174,67755,70876,67618,64257,64911,1.0%,-4.2%,34.2%,NaN
35,39000,Ohio,43548,41593,42673,44198,44911,45262,46671,47098,47419,48188,1.6%,6.5%,10.7%,NaN
36,40000,Oklahoma,40048,38640,38304,39972,41880,43317,45418,46370,44418,44535,0.3%,2.8%,11.2%,NaN
37,41000,Oregon,48508,47530,49614,51295,49461,48169,48130,49715,50751,51312,1.1%,6.5%,5.8%,NaN
38,42000,Pennsylvania,46862,45312,46391,46877,47554,48289,49228,50489,50978,51841,1.7%,7.4%,10.6%,NaN
39,44000,Rhode Island,45746,45280,46339,46023,46194,46367,46663,47519,47662,48314,1.4%,4.2%,5.6%,NaN
40,45000,South Carolina,36834,34955,35126,35608,35359,35716,36325,36952,37269,37637,1.0%,5.4%,2.2%,NaN
41,46000,South Dakota,45516,45457,45610,48034,47070,47003,47039,47980,48306,48004,-0.6%,2.1%,5.5%,NaN
42,47000,Tennessee,40949,39096,39375,40201,41114,41513,41858,42902,43720,44348,1.4%,6.8%,8.3%,NaN
43,48000,Texas,48282,47034,47422,48358,50253,52007,52879,54200,53104,53737,1.2%,3.3%,11.3%,NaN
44,49000,Utah,43375,41563,41501,42002,41952,42306,43264,44392,44947,45493,1.2%,7.5%,4.9%,NaN
45,50000,Vermont,41764,40855,42180,43160,43099,42989,43222,43605,44354,44831,1.1%,4.3%,7.3%,NaN
46,51000,Virginia,51985,51389,51949,51770,51568,51112,50855,51486,51443,52124,1.3%,2.0%,0.3%,NaN
47,53000,Washington,54939,52264,52694,52526,53473,54197,55338,56617,57796,59333,2.7%,9.5%,8.0%,NaN
48,54000,West Virginia,34679,34564,35367,36086,35532,35772,36017,36233,36155,37353,3.3%,4.4%,7.7%,NaN
49,55000,Wisconsin,44622,43215,44125,44936,45422,45895,46456,47268,48063,48666,1.3%,6.0%,9.1%,NaN
50,56000,Wyoming,69182,66320,64618,63999,60794,60806,60853,61304,59327,61091,3.0%,0.5%,-11.7%,NaN

In [13]:
gdp1=gdp.drop ('Unnamed: 15', axis=1)

In [14]:
col=gdp1.loc[:, "2008":"2017"]
gdp1['gdp_mean']=col.mean(axis=1)
gdp1

,Fips,Area,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,1-year (2016-2017),5-year (2013-2017),10-year (2008-2017),gdp_mean
0,1000,Alabama,36976,35376,35912,36210,36440,36674,36473,36818,37158,37508,0.9%,2.3%,1.4%,36554.5
1,2000,Alaska,67527,72204,69565,70618,73505,69711,67179,65971,63304,63610,0.5%,-8.8%,-5.8%,68319.4
2,4000,Arizona,41800,38232,37943,38267,38591,38352,38534,38787,38940,39583,1.7%,3.2%,-5.3%,38902.9
3,5000,Arkansas,34957,33837,34674,35156,34982,35888,36265,36295,36502,36714,0.6%,2.3%,5.0%,35527.0
4,6000,California,54454,51733,51878,52105,52963,53838,55571,57637,58974,60359,2.3%,12.1%,10.8%,54951.2
5,8000,Colorado,51651,49731,49260,49303,49673,50523,52105,53007,52863,54026,2.2%,6.9%,4.6%,51214.2
6,9000,Connecticut,68777,65574,64901,63602,63433,62438,62023,62796,62745,62633,-0.2%,0.3%,-8.9%,63892.2
7,10000,Delaware,62535,64313,62844,63795,62182,60738,63555,64809,63578,63955,0.6%,5.3%,2.3%,63230.4
8,11000,District of Columbia,170687,166178,168070,166908,163196,159264,159369,159530,159141,159607,0.3%,0.2%,-6.5%,163195.0
9,12000,Florida,41241,38695,38610,37875,37711,38018,38466,39334,39608,39842,0.6%,4.8%,-3.4%,38940.0
10,13000,Georgia,44239,42052,42032,42144,42206,42513,43467,44246,45238,45925,1.5%,8.0%,3.8%,43406.2
11,15000,Hawaii,50833,48549,49422,49314,49479,49484,49591,51052,51964,52869,1.7%,6.8%,4.0%,50255.7
12,16000,Idaho,36691,34664,34622,34291,34121,34787,35173,35679,36256,36441,0.5%,4.8%,-0.7%,35272.5
13,17000,Illinois,51406,49859,50306,51189,52141,51919,52984,53709,54308,55102,1.5%,6.1%,7.2%,52292.3
14,18000,Indiana,43515,40572,43000,43066,43077,43876,44818,44721,45717,46427,1.6%,5.8%,6.7%,43878.9
15,19000,Iowa,46413,45195,45891,46546,48031,48034,49688,51379,52248,52284,0.1%,8.8%,12.6%,48570.9
16,20000,Kansas,46050,43770,44250,45488,45513,45468,46235,46792,47548,47435,-0.2%,4.3%,3.0%,45854.9
17,21000,Kentucky,37875,36209,37585,37933,38062,38259,38336,38419,38736,39277,1.4%,2.7%,3.7%,38069.1
18,22000,Louisiana,46578,46949,48601,45722,45489,43721,44475,44751,44440,44372,-0.2%,1.5%,-4.7%,45509.8
19,23000,Maine,38508,37910,38357,37787,37727,37508,38149,38415,39125,39521,1.0%,5.4%,2.6%,38300.7
20,24000,Maryland,52877,52515,53679,54213,53999,53751,54108,54661,55786,56375,1.1%,4.9%,6.6%,54196.4
21,25000,Massachusetts,60723,59178,60814,61766,62441,61842,62528,64660,65168,66500,2.0%,7.5%,9.5%,62562.0
22,26000,Michigan,39863,36676,38766,39758,40465,40992,41544,42594,43330,44201,2.0%,7.8%,10.9%,40818.9
23,27000,Minnesota,51234,48884,50153,50899,51297,52023,53109,53257,54295,54805,0.9%,5.3%,7.0%,51995.6
24,28000,Mississippi,33128,31658,31687,31175,31807,31952,31635,31714,32334,32447,0.3%,1.5%,-2.1%,31953.7
25,29000,Missouri,43118,42012,42207,41601,41941,42498,42527,42785,42736,43036,0.7%,1.3%,-0.2%,42446.1
26,30000,Montana,37636,36667,37738,38578,38601,38567,39319,40148,40041,39833,-0.5%,3.3%,5.8%,38712.8
27,31000,Nebraska,47770,47973,49571,51378,50655,51597,53109,54048,54660,54654,0.0%,5.9%,14.4%,51541.5
28,32000,Nevada,49286,44774,44597,44559,43384,43074,43075,44057,44142,44812,1.5%,4.0%,-9.1%,44576.0
29,33000,New Hampshire,47842,47265,48395,48509,48661,48873,49623,51020,51827,52509,1.3%,7.4%,9.8%,49452.4
30,34000,New Jersey,57784,55067,55023,54281,55106,55659,55563,56196,56428,56776,0.6%,2.0%,-1.7%,55788.3
31,35000,New Mexico,41207,40670,40300,40167,40098,39659,40769,41457,41334,41619,0.7%,4.9%,1.0%,40728.0
32,36000,New York,58532,59481,61259,61163,62769,62320,63174,64286,64522,65220,1.1%,4.7%,11.4%,62272.6
33,37000,North Carolina,45567,43160,43071,43169,42619,42909,43400,44180,44194,44706,1.2%,4.2%,-1.9%,43697.5
34,38000,North Dakota,48379,48858,52186,57120,68174,67755,70876,67618,64257,64911,1.0%,-4.2%,34.2%,61013.4
35,39000,Ohio,43548,41593,42673,44198,44911,45262,46671,47098,47419,48188,1.6%,6.5%,10.7%,45156.1
36,40000,Oklahoma,40048,38640,38304,39972,41880,43317,45418,46370,44418,44535,0.3%,2.8%,11.2%,42290.2
37,41000,Oregon,48508,47530,49614,51295,49461,48169,48130,49715,50751,51312,1.1%,6.5%,5.8%,49448.5
38,42000,Pennsylvania,46862,45312,46391,46877,47554,48289,49228,50489,50978,51841,1.7%,7.4%,10.6%,48382.1
39,44000,Rhode Island,45746,45280,46339,46023,46194,46367,46663,47519,47662,48314,1.4%,4.2%,5.6%,46610.7
40,45000,South Carolina,36834,34955,35126,35608,35359,35716,36325,36952,37269,37637,1.0%,5.4%,2.2%,36178.1
41,46000,South Dakota,45516,45457,45610,48034,47070,47003,47039,47980,48306,48004,-0.6%,2.1%,5.5%,47001.9
42,47000,Tennessee,40949,39096,39375,40201,41114,41513,41858,42902,43720,44348,1.4%,6.8%,8.3%,41507.6
43,48000,Texas,48282,47034,47422,48358,50253,52007,52879,54200,53104,53737,1.2%,3.3%,11.3%,50727.6
44,49000,Utah,43375,41563,41501,42002,41952,42306,43264,44392,44947,45493,1.2%,7.5%,4.9%,43079.5
45,50000,Vermont,41764,40855,42180,43160,43099,42989,43222,43605,44354,44831,1.1%,4.3%,7.3%,43005.9
46,51000,Virginia,51985,51389,51949,51770,51568,51112,50855,51486,51443,52124,1.3%,2.0%,0.3%,51568.1
47,53000,Washington,54939,52264,52694,52526,53473,54197,55338,56617,57796,59333,2.7%,9.5%,8.0%,54917.7
48,54000,West Virginia,34679,34564,35367,36086,35532,35772,36017,36233,36155,37353,3.3%,4.4%,7.7%,35775.8
49,55000,Wisconsin,44622,43215,44125,44936,45422,45895,46456,47268,48063,48666,1.3%,6.0%,9.1%,45866.8
50,56000,Wyoming,69182,66320,64618,63999,60794,60806,60853,61304,59327,61091,3.0%,0.5%,-11.7%,62829.4

In [15]:
gdp1.rename(columns={'Area': 'State'}, inplace=True)
gdp1.head()

,Fips,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,1-year (2016-2017),5-year (2013-2017),10-year (2008-2017),gdp_mean
0,1000,Alabama,36976,35376,35912,36210,36440,36674,36473,36818,37158,37508,0.9%,2.3%,1.4%,36554.5
1,2000,Alaska,67527,72204,69565,70618,73505,69711,67179,65971,63304,63610,0.5%,-8.8%,-5.8%,68319.4
2,4000,Arizona,41800,38232,37943,38267,38591,38352,38534,38787,38940,39583,1.7%,3.2%,-5.3%,38902.9
3,5000,Arkansas,34957,33837,34674,35156,34982,35888,36265,36295,36502,36714,0.6%,2.3%,5.0%,35527.0
4,6000,California,54454,51733,51878,52105,52963,53838,55571,57637,58974,60359,2.3%,12.1%,10.8%,54951.2

In [16]:
gdp1.to_csv('GDP_PerCapita.csv')

In [17]:
df2=pd.read_csv ('school_perstudent.csv')
df2

,State,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,United States,"5,123","5,280","5,483","5,646","5,880","6,148","6,460","6,860","7,321",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alabama,"3,572","3,826","4,109","4,343","4,595","4,849","5,188","5,638","5,885",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alaska,"7,901","7,960","8,033","8,189","8,231","8,271","8,404","8,806","9,216",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arizona,"4,088","4,104","4,264","4,476","4,413","4,595","4,672","5,030","5,278",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arkansas,"3,859","4,013","4,186","4,401","4,535","4,708","4,956","5,277","5,568",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,California,"4,614","4,718","4,799","4,937","5,260","5,644","5,801","6,314","6,987",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Colorado,"4,766","4,727","5,047","5,121","5,312","5,656","5,923","6,215","6,567",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Connecticut,"7,652","7,947","8,380","8,430","8,580","8,904","9,318","9,753","10,127",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Delaware,"5,750","6,101","6,502","6,696","7,135","7,420","7,706","8,310","8,958",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,District of Columbia,"8,286","8,843","8,290","8,510","8,048","8,393","9,650","10,107","12,046",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Florida,"4,876","5,063","5,220","5,275","5,360","5,552","5,790","5,831","6,170",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Georgia,"4,368","4,569","4,828","5,056","5,369","5,647","6,092","6,437","6,929",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Hawaii,"5,332","5,532","5,597","5,560","5,633","5,858","6,081","6,530","6,596",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Idaho,"3,471","3,628","3,957","4,194","4,447","4,721","5,066","5,315","5,725",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Illinois,"5,307","5,323","5,553","5,519","5,940","6,242","6,762","7,133","7,643",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Indiana,"4,995","5,245","5,411","5,621","6,161","6,318","6,772","7,192","7,630",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Iowa,"4,970","5,070","5,240","5,481","5,738","5,998","6,243","6,564","6,930",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Kansas,"4,926","5,081","5,222","5,374","5,508","5,727","6,015","6,294","6,925",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Kentucky,"4,311","4,505","4,545","4,807","5,155","5,213","5,560","5,921","6,079",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Louisiana,"4,010","4,133","4,356","4,447","4,724","5,188","5,548","5,804","6,037",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Maine,"5,624","5,569","6,029","6,151","6,327","6,742","7,155","7,667","8,232",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Maryland,"6,060","6,191","6,427","6,593","6,755","7,034","7,326","7,731","8,256",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Massachusetts,"6,141","6,423","6,783","7,033","7,331","7,778","8,260","8,816","9,509",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Michigan,"5,945","6,138","6,465","6,785","6,932","7,050","7,432","8,110","8,278",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Minnesota,"5,210","5,342","5,626","5,801","6,005","6,388","6,791","7,190","7,645",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Mississippi,"3,159","3,410","3,798","3,951","4,039","4,288","4,565","5,014","5,175",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Missouri,"4,318","4,547","4,866","5,092","5,304","5,565","5,855","6,187","6,657",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Montana,"4,907","5,043","5,137","5,249","5,481","5,724","5,974","6,314","6,726",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Nebraska,"5,064","5,310","5,555","5,688","5,848","5,958","6,256","6,683","7,223",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Nevada,"4,645","4,661","4,730","4,892","5,084","5,295","5,587","5,760","5,807",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,New Hampshire,"5,368","5,433","5,567","5,740","5,920","6,156","6,433","6,860","7,286",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,New Jersey,"8,770","9,075","9,178","9,361","9,588","9,643","10,145","10,337","11,248",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,New Mexico,"3,929","4,106","4,412","4,604","4,682","5,005","5,440","5,825","6,313",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,New York,"7,770","8,069","8,311","8,361","8,525","8,852","9,344","9,846","10,716",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,North Carolina,"4,426","4,540","4,703","4,719","4,929","5,257","5,656","6,045","6,346",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,North Dakota,"4,284","4,385","4,463","4,677","4,808","5,056","5,442","5,667","6,125",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Ohio,"5,332","5,319","5,529","5,669","5,935","6,198","6,627","7,065","7,571",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Oklahoma,"4,090","4,403","4,533","4,549","4,817","5,033","5,303","5,395","6,019",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Oregon,"5,585","5,522","5,649","5,790","5,920","6,419","6,828","7,149","7,528",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Pennsylvania,"6,372","6,443","6,565","6,922","7,106","7,209","7,450","7,772","8,210",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Rhode Island,"6,501","6,797","6,899","7,304","7,612","7,928","8,294","8,904","9,315",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,South Carolina,"4,204","4,335","4,501","4,779","5,050","5,320","5,656","6,130","6,631",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,South Dakota,"4,109","4,095","4,271","4,220","4,375","4,669","5,259","5,632","6,191",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Tennessee,"3,674","3,813","4,017","4,172","4,581","4,937","5,123","5,383","5,687",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Texas,"4,270","4,488","4,779","5,016","5,267","5,444","5,685","6,288","6,539",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Utah,"2,967","3,206","3,409","3,604","3,783","3,969","4,210","4,378","4,674",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Vermont,"6,342","6,266","6,367","6,488","6,753","7,075","7,541","8,323","9,153",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Virginia,"5,066","5,205","5,421","5,528","5,788","6,067","6,350","6,841","7,281",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Washington,"5,220","5,342","5,477","5,611","5,734","6,040","6,110","6,376","6,750",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,West Virginia,"5,108","5,292","5,663","5,881","6,076","6,323","6,677","7,152","7,534",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Wisconsin,"5,974","6,126","6,301","6,517","6,796","7,123","7,527","7,806","8,243",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Wyoming,"5,462","5,534","5,753","5,826","5,971","6,218","6,842","7,425","7,835",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
School=df2.drop(df2.loc[:,'Unnamed: 25':'Unnamed: 50'].head(0).columns, axis=1)

In [19]:
school_per_student=School.drop(School.loc[:, '1993': '2007'].head(0).columns, axis=1)
school_per_student

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,United States,"10,249","10,503","10,601","10,625","10,617","10,744","11,036","11,408","11,791"
1,Alabama,"9,197","8,964","8,907","8,726","8,577","8,773","9,036","9,146","9,258"
2,Alaska,"14,641","15,363","15,829","16,663","17,475","18,217","18,466","20,191","17,510"
3,Arizona,"7,727","8,022","7,870","7,782","7,383","7,495","7,427","7,530","7,711"
4,Arkansas,"8,677","8,854","9,281","9,496","9,536","9,538","9,752","9,805","9,900"
5,California,"9,706","9,503","9,300","9,146","9,220","9,258","9,671","10,449","11,419"
6,Colorado,"9,152","8,782","8,926","8,786","8,594","8,693","9,036","9,292","9,619"
7,Connecticut,"14,610","15,353","15,698","16,224","16,855","17,321","18,401","19,020","19,615"
8,Delaware,"12,153","12,109","12,222","12,467","13,580","13,653","13,793","13,882","14,397"
9,District of Columbia,"16,353","19,698","20,910","20,793","19,847","20,451","20,537","20,610","21,135"
10,Florida,"9,084","8,867","8,863","9,030","8,520","8,623","8,955","9,113","9,176"
11,Georgia,"9,718","9,649","9,432","9,259","9,272","9,121","9,236","9,476","9,835"
12,Hawaii,"11,800","12,400","11,855","11,924","11,973","11,790","12,400","12,855","13,748"
13,Idaho,"6,951","7,118","7,100","6,821","6,626","6,761","6,577","6,929","7,178"
14,Illinois,"10,353","11,084","11,737","11,739","12,008","12,439","13,203","13,923","14,327"
15,Indiana,"8,867","9,254","9,479","9,251","9,588","9,421","9,396","9,529","9,691"
16,Iowa,"9,275","9,704","9,748","9,795","10,027","10,291","10,647","10,938","11,148"
17,Kansas,"9,894","10,204","9,972","9,802","10,021","10,011","10,240","10,329","10,216"
18,Kentucky,"8,740","8,786","8,957","9,228","9,327","9,274","9,411","9,560","9,831"
19,Louisiana,"10,006","10,625","10,701","10,799","10,726","10,539","10,853","11,106","11,169"
20,Maine,"11,761","12,183","12,525","12,576","12,335","12,694","13,267","13,911","14,202"
21,Maryland,"13,257","13,737","14,007","13,946","13,875","14,086","14,217","14,431","14,523"
22,Massachusetts,"13,690","14,534","13,956","14,612","14,844","15,321","15,886","16,450","16,986"
23,Michigan,"10,075","10,373","10,447","10,577","10,477","10,515","10,649","10,956","11,051"
24,Minnesota,"10,060","10,983","10,665","10,674","10,781","11,065","11,427","11,924","12,364"
25,Mississippi,"7,890","8,064","8,104","7,926","8,097","8,117","8,265","8,445","8,692"
26,Missouri,"9,297","9,617","9,721","9,461","9,514","9,702","9,938","10,231","10,385"
27,Montana,"9,749","10,120","10,565","10,719","10,569","10,662","10,941","11,078","11,374"
28,Nebraska,"10,199","10,436","10,880","11,208","11,492","11,743","11,877","12,174","12,379"
29,Nevada,"8,187","8,321","8,376","8,411","8,130","8,026","8,275","8,451","8,753"
30,New Hampshire,"11,951","12,583","13,072","13,548","13,774","14,050","14,601","14,969","15,535"
31,New Jersey,"17,620","16,973","17,379","16,855","17,982","18,523","18,780","18,559","19,041"
32,New Mexico,"9,291","9,648","9,621","9,250","9,013","9,164","9,403","9,724","9,959"
33,New York,"16,794","17,746","18,167","18,857","19,396","19,529","20,156","20,744","21,818"
34,North Carolina,"7,709","8,463","8,225","8,267","8,160","8,342","8,287","8,529","8,717"
35,North Dakota,"9,324","9,802","10,519","10,898","11,246","11,615","12,383","12,884","13,358"
36,Ohio,"10,340","10,669","11,224","11,395","11,323","11,276","11,434","11,730","11,933"
37,Oklahoma,"7,683","7,878","7,929","7,631","7,763","7,914","7,995","8,075","8,091"
38,Oregon,"9,565","9,611","9,268","9,516","9,485","9,183","9,524","9,927","10,247"
39,Pennsylvania,"11,741","12,299","12,729","13,096","13,091","13,445","13,824","14,405","15,165"
40,Rhode Island,"14,459","14,719","14,723","14,948","15,172","14,889","15,372","15,797","16,082"
41,South Carolina,"9,060","9,228","9,080","8,908","9,102","9,444","9,608","9,831","10,045"
42,South Dakota,"8,535","8,543","9,020","8,931","8,593","8,630","9,036","9,103","9,335"
43,Tennessee,"7,820","7,992","8,117","8,330","8,348","8,588","8,662","8,776","8,876"
44,Texas,"8,350","8,562","8,788","8,685","8,213","8,285","8,602","9,081","9,352"
45,Utah,"5,978","6,500","6,360","6,326","6,312","6,432","6,546","6,751","7,006"
46,Vermont,"14,421","15,096","15,666","14,707","16,651","17,286","18,066","18,769","19,023"
47,Virginia,"10,664","10,928","10,594","10,363","10,656","10,960","10,955","11,235","11,435"
48,Washington,"9,058","9,585","9,497","9,619","9,604","9,714","10,305","10,684","11,484"
49,West Virginia,"10,059","10,606","11,774","11,978","11,579","11,264","11,371","11,512","11,424"
50,Wisconsin,"10,709","11,097","11,423","11,846","11,141","11,186","11,345","11,538","11,664"
51,Wyoming,"13,790","14,552","15,140","15,711","15,896","15,722","15,815","16,047","16,431"

In [11]:
df2.to_csv('school-expense-per-student.csv')

In [26]:
merged_gdp_school=pd.merge(gdp1, school_per_student , on='State')

In [28]:
merged_gdp_school.to_csv('merged_gdp_school.csv')